
device: 'cuda'

target:
  name: "phi4"
  dim: 256
  phi4_1:
    positive: true
    sample_path: data/phi4_umbrella_pos.pt
  phi4_2:
    positive: false
    sample_path: data/phi4_umbrella_neg.pt

network:
  name: 'mlp'
  learn_b: true
  score_net:
    num_layer: 5
    num_hid: 400
    clip: 10000
  vector_field:
    num_layer: 5
    num_hid: 400
    clip: 10000

coef:
  alpha: '1-t'
  beta: 't'
  gamma: 'sqrt(a*t*(1-t))+b'
  b: 0.0001
  a: 0.05
  eps: 0.01

train:
  lr: 0.001
  num_epoch: 100000
  batch_size: 1000
  OT_pair: true
  ema_rate: 0.995

  finetune: false

sample:
  num_step: 500

save:
  save_dir: "results"
  eval_gap: 10000
  eval_sample: 90000
  eval_batch: 5000
